services:
    _defaults:
        autowire: true
        autoconfigure: true

    Hengebytes\WebserviceCoreAsyncBundle\:
        resource: '../../'
        exclude:
            - '../../Callback'
            - '../../Collection'
            - '../../Cache'
            - '../../DependencyInjection'
            - '../../Enum'
            - '../../Exception'
            - '../../Logs'
            - '../../Model'
            - '../../Provider/ParamsProvider'
            - '../../Request'
            - '../../Resources'
            - '../../Response'
            - '../../HBWebserviceCoreAsyncBundle.php'


